services:
  postgres:
    image: postgres:16
    container_name: index_searcher_postgres
    environment:
      POSTGRES_DB: index_searcher_db
      POSTGRES_USER: a_user
      POSTGRES_PASSWORD: pass123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a_user -d index_searcher_db"]
      interval: 10s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7-alpine
    container_name: index_searcher_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  crawler:
    build: .
    container_name: wiki_crawler
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      tests:
        condition: service_completed_successfully
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: index_searcher_db
      DATABASE_USER: a_user
      DATABASE_PASSWORD: pass123
      CRAWLER_START_URL: "https://pl.wikipedia.org/wiki/Toru%C5%84"
      CRAWLER_USER_AGENT: "index-searcher/1.0 (+https://github.com/d4krzyk)"
      CRAWLER_ROBOTS_AGENT: "*"               # domyślnie '*' lub inny agent
      CRAWLER_MAX_DEPTH: "2"
      CRAWLER_DELAY: "1.0"
      CRAWLER_ALLOWED_DOMAIN: "pl.wikipedia.org"

      # rate limiting / redis
      CRAWLER_REDIS_URL: "redis://redis:6379"
      CRAWLER_RATE_PER_SEC: "10"
      CRAWLER_RATE_KEY: "wiki_crawler"
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - ./app:/app
    command: python /app/crawler.py
    stdin_open: false
    tty: false
    restart: "no"

  indexer:
    build: .
    container_name: index_searcher_indexer
    depends_on:
      postgres:
        condition: service_healthy
      crawler:
        condition: service_completed_successfully
      tests:
        condition: service_completed_successfully
    environment:
      SMOOTH_IDF: 1
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: index_searcher_db
      DATABASE_USER: a_user
      DATABASE_PASSWORD: pass123
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - ./app:/app
    command: python /app/indexer.py
    stdin_open: false
    tty: false
    restart: "no"

  searcher:
    build: .
    container_name: index_searcher_searcher
    depends_on:
      postgres:
        condition: service_healthy
      tests:
        condition: service_completed_successfully
    environment:
      SMOOTH_IDF: 1
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: index_searcher_db
      DATABASE_USER: a_user
      DATABASE_PASSWORD: pass123
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - ./app:/app
    entrypoint: ["python", "/app/searcher.py"]
    stdin_open: true
    tty: true
    restart: "no"

  tests:
    build: .
    container_name: index_searcher_tests
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SMOOTH_IDF: 1
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: index_searcher_db
      DATABASE_USER: a_user
      DATABASE_PASSWORD: pass123
      PYTHONPATH: /app
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    working_dir: /app
    volumes:
      - ./app:/app
      - ./tests:/app/tests:ro
    command: pytest -q tests
    stdin_open: false
    tty: false
    restart: "no"

volumes:
  pgdata:
